package uauthn

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestCaddyHashCompatibility(t *testing.T) {
	const hash = "$argon2id$v=19$m=47104,t=1,p=1$xgHKb6CaW1IP33D4qswVpA$wn228HVYF79WKyr5z4KjUXR5VSRxETnZcwFlbmk6pBw"
	if !VerifyPassword(hash, "caddy-compat") {
		t.Fatal("hash generated by caddy hash-password was rejected")
	}
	if VerifyPassword(hash, "wrong") {
		t.Fatal("wrong password accepted")
	}
	h, err := HashPassword("secret")
	if err != nil || !VerifyPassword(h, "secret") {
		t.Fatalf("round trip failed: %v", err)
	}
}

func TestConfig(t *testing.T) {
	path := filepath.Join(t.TempDir(), "config")
	os.WriteFile(path, []byte("# comment\nport = 8080\nprefix = auth/\nsession = storage\ndomain=example.com\n"), 0o600)
	c, err := LoadConfig(path)
	if err != nil {
		t.Fatal(err)
	}
	if c.Port != 8080 || c.Prefix != "/auth" || c.Session != SessionFileMode || c.Domain != "example.com" || c.Bind != "0.0.0.0" {
		t.Fatalf("unexpected config %+v", c)
	}
	os.WriteFile(path, []byte("unknown = 1\n"), 0o600)
	if _, err := LoadConfig(path); err == nil {
		t.Fatal("unknown key accepted")
	}
}

func TestPasswd(t *testing.T) {
	path := filepath.Join(t.TempDir(), "passwd")
	os.WriteFile(path, []byte("# users\nalice\tpasskey:AQID:-7:BAUG\textra\n"), 0o600)
	u := NewUsers(path)
	if _, err := u.SetPassword("alice", "$argon2id$x", false); err != nil {
		t.Fatal(err)
	}
	if created, _ := u.SetPassword("bob", "$argon2id$y", false); !created {
		t.Fatal("bob not created")
	}
	got, _ := os.ReadFile(path)
	want := "# users\nalice\t$argon2id$x\tpasskey:AQID:-7:BAUG\textra\nbob\t$argon2id$y\n"
	if string(got) != want {
		t.Fatalf("got %q, want %q", got, want)
	}
	if user, pk, ok := u.FindPasskey([]byte{1, 2, 3}); !ok || user != "alice" || pk.Alg != -7 {
		t.Fatalf("FindPasskey: %v %v %v", user, pk, ok)
	}
	u.SetPassword("alice", "$argon2id$z", true)
	got, _ = os.ReadFile(path)
	if !strings.Contains(string(got), "alice\t$argon2id$z\n") {
		t.Fatalf("reset failed: %q", got)
	}
}

func TestSessionFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "session.dat")
	s := NewSessions(FileBackend{Path: path}, time.Hour, t.Logf)
	v, _ := s.Create("alice")
	user, key, ok := ParseSessionValue(v)
	if !ok || user != "alice" || !s.Check(user, key, time.Hour) {
		t.Fatal("session not valid")
	}
	s.Flush()
	st, _ := os.Stat(path)
	if st.Size() != sessionHeader+sessionBlock*sessionRecord {
		t.Fatalf("size %d", st.Size())
	}

	other := NewSessions(FileBackend{Path: path}, time.Hour, t.Logf)
	if !other.Check(user, key, time.Hour) {
		t.Fatal("session not loaded from file")
	}
	v2, _ := other.Create("bob")
	other.Flush()
	time.Sleep(20 * time.Millisecond)
	s.Delete(user, key)
	s.Flush()
	_, key2, _ := ParseSessionValue(v2)
	if !s.Check("bob", key2, time.Hour) {
		t.Fatal("merge lost bob")
	}
	if s.Check(user, key, time.Hour) {
		t.Fatal("deleted session resurrected")
	}
	other.Close()
	s.Close()

	m := map[sessionID]int64{}
	for i := 0; i < 17; i++ {
		m[sessionID{byte(i + 1)}] = int64(i + 1)
	}
	if n := len(encodeSessions(m)); n != sessionHeader+32*sessionRecord {
		t.Fatalf("17 sessions encoded to %d bytes", n)
	}
	os.WriteFile(path, []byte("broken"), 0o600)
	s = NewSessions(FileBackend{Path: path}, time.Hour, func(string, ...any) {})
	s.Close()
	if data, _ := os.ReadFile(path); len(data) != sessionHeader+sessionBlock*sessionRecord {
		t.Fatalf("invalid file not overwritten: %d bytes", len(data))
	}
}

type authenticator struct {
	alg  int
	sign func(msg []byte) []byte
	spki []byte
	id   []byte
}

func newAuthenticator(t *testing.T, alg int) *authenticator {
	a := &authenticator{alg: alg, id: []byte{byte(-alg), 9, 9}}
	var pub any
	switch alg {
	case algES256:
		k, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		pub = &k.PublicKey
		a.sign = func(msg []byte) []byte {
			d := sha256.Sum256(msg)
			s, _ := ecdsa.SignASN1(rand.Reader, k, d[:])
			return s
		}
	case algRS256:
		k, _ := rsa.GenerateKey(rand.Reader, 2048)
		pub = &k.PublicKey
		a.sign = func(msg []byte) []byte {
			d := sha256.Sum256(msg)
			s, _ := rsa.SignPKCS1v15(rand.Reader, k, crypto.SHA256, d[:])
			return s
		}
	case algEdDSA:
		p, k, _ := ed25519.GenerateKey(rand.Reader)
		pub = p
		a.sign = func(msg []byte) []byte { return ed25519.Sign(k, msg) }
	}
	var err error
	if a.spki, err = x509.MarshalPKIXPublicKey(pub); err != nil {
		t.Fatal(err)
	}
	return a
}

func (a *authenticator) response(typ, challenge, origin, rpID string) (cdj, ad, sig []byte) {
	cdj, _ = json.Marshal(map[string]any{"type": typ, "challenge": challenge, "origin": origin})
	h := sha256.Sum256([]byte(rpID))
	ad = append(h[:], 0x05, 0, 0, 0, 0)
	cdh := sha256.Sum256(cdj)
	return cdj, ad, a.sign(append(append([]byte{}, ad...), cdh[:]...))
}

func TestServerFlow(t *testing.T) {
	dir := t.TempDir()
	users := NewUsers(filepath.Join(dir, "passwd"))
	hash, _ := HashPassword("pw")
	users.SetPassword("alice", hash, false)
	sessions := NewSessions(nil, time.Hour, t.Logf)
	srv := NewServer(Options{Prefix: "/uauthn", Expire: time.Hour, Users: users, Sessions: sessions, Logf: t.Logf})
	h := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		p, _ := srv.StripPrefix(r.URL.Path)
		srv.Handle(w, r, p)
	})
	const origin = "http://example.test"

	do := func(method, path string, body any, cookie *http.Cookie) *httptest.ResponseRecorder {
		var b bytes.Buffer
		if body != nil {
			json.NewEncoder(&b).Encode(body)
		}
		r := httptest.NewRequest(method, origin+path, &b)
		if cookie != nil {
			r.AddCookie(cookie)
		}
		w := httptest.NewRecorder()
		h.ServeHTTP(w, r)
		return w
	}

	if w := do("POST", "/uauthn/login", map[string]string{"type": "password", "username": "alice", "password": "bad"}, nil); w.Code != 401 {
		t.Fatalf("bad password: %d", w.Code)
	}
	w := do("POST", "/uauthn/login", map[string]string{"type": "password", "username": "alice", "password": "pw"}, nil)
	if w.Code != 200 {
		t.Fatalf("login: %d %s", w.Code, w.Body)
	}
	cookie := w.Result().Cookies()[0]
	r := httptest.NewRequest("GET", origin+"/", nil)
	r.AddCookie(cookie)
	if user, ok := srv.Authenticate(r); !ok || user != "alice" {
		t.Fatal("cookie not accepted")
	}

	for _, alg := range []int{algES256, algRS256, algEdDSA} {
		a := newAuthenticator(t, alg)
		var st map[string]any
		json.Unmarshal(do("GET", "/uauthn/challenge", nil, cookie).Body.Bytes(), &st)
		if st["user"] != "alice" {
			t.Fatalf("challenge state %v", st)
		}
		cdj, ad, _ := a.response("webauthn.create", st["challenge"].(string), origin, "example.test")
		reg := map[string]any{"id": b64url.EncodeToString(a.id), "clientDataJSON": b64url.EncodeToString(cdj),
			"authenticatorData": b64url.EncodeToString(ad), "publicKey": b64url.EncodeToString(a.spki), "alg": alg}
		if w := do("POST", "/uauthn/passkey", reg, cookie); w.Code != 200 {
			t.Fatalf("register alg %d: %d %s", alg, w.Code, w.Body)
		}

		json.Unmarshal(do("GET", "/uauthn/challenge", nil, nil).Body.Bytes(), &st)
		cdj, ad, sig := a.response("webauthn.get", st["challenge"].(string), origin, "example.test")
		login := map[string]any{"type": "passkey", "id": b64url.EncodeToString(a.id), "clientDataJSON": b64url.EncodeToString(cdj),
			"authenticatorData": b64url.EncodeToString(ad), "signature": b64url.EncodeToString(sig)}
		if w := do("POST", "/uauthn/login", login, nil); w.Code != 200 {
			t.Fatalf("passkey login alg %d: %d %s", alg, w.Code, w.Body)
		}
		if w := do("POST", "/uauthn/login", login, nil); w.Code != 401 {
			t.Fatalf("challenge reused for alg %d", alg)
		}
	}

	w = do("GET", "/uauthn/logout?rd=/x", nil, cookie)
	if w.Code != http.StatusFound || w.Header().Get("Location") != "/x" {
		t.Fatalf("logout: %d %s", w.Code, w.Header().Get("Location"))
	}
	if _, ok := srv.Authenticate(r); ok {
		t.Fatal("session survived logout")
	}
}
